import Head from 'next/head'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic'

const Test = dynamic(
  () => import('./DashBoard1'),
  { ssr: false}
)

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        
        <title>Production monitoring</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Test />
    </div>
  )
}
